Initial api endpoint
CS222-UIUC/RecipeBook-40 pull request #14
Opened 2024-10-24 22:18 UTC by zyunlam

2024-10-24 22:42 UTC, SnehaSinghSS commented
This is a good start for the recipe API endpoint, and as we go we can connect with Michael and figure out how to communicate with the database to get it fully functional

2024-10-26 19:44 UTC, mpkarpov-ui requested changes
API changes look good to me but the delta is a lil silly rn

2024-10-26 19:44 UTC, mpkarpov-ui commented on Front-End/login-signup/package-lock.json
Gitignore this

2024-10-26 19:44 UTC, mpkarpov-ui commented on compose.yml
Might need a rebase

2024-11-02 23:35 UTC, merged